---
language: node_js
node_js:
  - "4"

sudo: false

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - yarn global add bower phantomjs-prebuilt
  - bower --version
  - phantomjs --version

install:
  - yarn
  - bower install
